export const Images = {
   BreakFast1 : require('../../assets/images/breakfast/breakfast1.jpeg'),
   BreakFast2 : require('../../assets/images/breakfast/breakfast2.webp'),
   Cofee1 : require('../../assets/images/coffe/cofee1.webp'),
   Cofee2 : require('../../assets/images/coffe/cofee2.jpeg'),
   Cofee3 : require('../../assets/images/coffe/cofee3.webp'),
   CrameFrappe1 : require('../../assets/images/coffe/cramefrappe1.jpeg'),
   CrameFrappe2 : require('../../assets/images/coffe/cramelfrappe2.webp'),
   ChocoFrappe1 : require('../../assets/images/coffe/ChocoFrappe.webp'),
   CHOCOFRAPPE2 : require('../../assets/images/coffe/CHOCOFRAPPE2.jpeg'),
   Drinks1 : require('../../assets/images/drinks/drinks1.jpeg'),
   Drinks2 : require('../../assets/images/drinks/drinks2.jpeg'),
   Fries1 : require('../../assets/images/fries/fries1.webp'),
   Fries2 : require('../../assets/images/fries/fries2.webp'),
   Lunch1 : require('../../assets/images/lunch/lunch1.webp'),
   Lunch2 : require('../../assets/images/lunch/lunch2.jpeg'),
   Munchise1 : require('../../assets/images/munchise/munchise1.jpeg'),
   Munchise2 : require('../../assets/images/munchise/munchise2.jpeg'),
}